### ISSUE TITLE
Could not find de.fraunhofer.iem:PathExpression:1.0.0 dependency

### ISSUE THREAD

**Issue by tiganov** [CodeShield-Security/SPDS#15]
I'm attempting to use SPDS as a Gradle dependency following [this](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages#authenticating-to-github-packages) and [this](https://docs.gradle.org/current/userguide/declaring_repositories.html). I have 
```
implementation 'de.fraunhofer.iem:WPDS:3.0.8'
```
in my `build.gradle`. I don't think the issue is with Gradle because I am able to pull the base "WPDS" package, just not one of its dependencies. I have the following error when building
```
Execution failed for task '[...]'.
> Could not resolve all files for configuration '[...]'.
   > Could not find de.fraunhofer.iem:PathExpression:1.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.pom
       - https://repo.maven.apache.org/maven2/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.jar
       - https://jcenter.bintray.com/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.pom
       - https://jcenter.bintray.com/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.jar
       - https://maven.pkg.github.com/CodeShield-Security/SPDS/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.pom
       - https://maven.pkg.github.com/CodeShield-Security/SPDS/de/fraunhofer/iem/PathExpression/1.0.0/PathExpression-1.0.0.jar
```

**Comment by johspaeth** [comment]
Thanks for reporting. 

PathExpression is not yet deployed to GitHub/Maven. In the meantime you can download a compiled version here:
https://soot-build.cs.uni-paderborn.de/nexus/

or alternatively build from sources:
https://github.com/johspaeth/PathExpression

**Comment by tiganov** [comment]
Adding https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/ as a repository worked. Thanks.
