### ISSUE TITLE
Unable to install SPDS

### ISSUE THREAD

**Issue by lbettels** [CodeShield-Security/SPDS#37]
When i try to build SPDS, the server at https://soot-build.cs.uni-paderborn.de/nexus/repository/swt-upb/ throws an 502 Bad Gateway error.
Specifically it fails when i try to obtain the de.fraunhofer.iem:PathExpression:jar:1.0.0 jar file.
Could somebody help me solve this build problem?

Cheers!

**Comment by johspaeth** [comment]
Thanks for reporting. The build problem has been resolved on master - the package `pathexpression` has been renamed and this change hadn't been applied to master.
