### ISSUE TITLE
Boomerang crashes when summaries are enabled

### ISSUE THREAD

**Issue by dseekatz** [CodeShield-Security/SPDS#4]
Hi,

I am using Boomerang 3.0.10 and trying to run the provided examples, but with call summaries enabled.  The only change I have made to the examples is that I have replaced
```
          // 1. Create a Boomerang solver.
          Boomerang solver =
              new Boomerang(
                  sootCallGraph, SootDataFlowScope.make(Scene.v()), new DefaultBoomerangOptions());
```
with the following code:
```
        // 1. Create a Boomerang solver.
        Boomerang solver =
            new Boomerang(
                sootCallGraph,
                SootDataFlowScope.make(Scene.v()),
                new DefaultBoomerangOptions() {
                  @Override
                  public boolean callSummaries() {
                    return true;
                  }
                });
```

Running ExampleMain1 produces the following output:
```
<boomerang.example.BoomerangExampleTarget1: void <init>()>
<boomerang.example.BoomerangExampleTarget1: void main(java.lang.String[])>
<boomerang.example.BoomerangExampleTarget1: void staticCallOnFile(boomerang.example.BoomerangExampleTarget1$ClassWithField,boomerang.example.BoomerangExampleTarget1$NestedClassWithField)>
<boomerang.example.BoomerangExampleTarget1: void queryFor(boomerang.example.BoomerangExampleTarget1$ObjectOfInterest)>
Solving query: BackwardQuery: (queryVariable (boomerang.example.BoomerangExampleTarget1.<boomerang.example.BoomerangExampleTarget1: void staticCallOnFile(boomerang.example.BoomerangExampleTarget1$ClassWithField,boomerang.example.BoomerangExampleTarget1$NestedClassWithField)>),RS: queryFor(queryVariable))
Boomerang CRASHEDjava.lang.NullPointerException
All allocation sites of the query variable are:
{}
All aliasing access path of the query variable are:
[]
```

The null pointer exception occurs when Boomerang [tries to retrieve a summary automaton](https://github.com/CodeShield-Security/SPDS/blob/38c13cc6f093ecfe2d847a1aef06810b72b977dd/WPDS/src/main/java/wpds/impl/WeightedPushdownSystem.java#L146) during post*, but no summaries have been created yet at this point.  I can also provide the whole stack trace if it helps, but it is quite long.

Is there some additional way that I need to configure Boomerang before I can use summaries?

Thanks,
David

**Comment by dseekatz** [comment]
Thanks @copumpkin for pinging @johspaeth, and thanks @johspaeth for the excellent detailed explanation.

> Conceptually, one needs to take aliasing into account at the time the summaries are applied. This is something that Boomerang does not yet support.

I assume it would be very tricky to implement this efficiently for a demand-driven analysis framework like Boomerang?

**Comment by johspaeth** [comment]
> I assume it would be very tricky to implement this efficiently for a demand-driven analysis framework like Boomerang?

I have some concepts and ideas for summarization that need to be implemented. But certainly not an easy task.
